spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cogito
        username: bootuser
        password: bootuser
    jpa:
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update
        show-sql: true